# Generated by Django 3.0.7 on 2020-06-25 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LevelData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClassData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.LevelData')),
            ],
        ),
        migrations.CreateModel(
            name='ClassContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributer_name', models.TextField(max_length=100)),
                ('contributer_image', models.ImageField(upload_to='media/ContributerImage')),
                ('link_to_youtube', models.URLField()),
                ('linked_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.ClassData')),
            ],
        ),
    ]
