# Generated by Django 3.0.7 on 2020-06-25 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdata',
            name='class_id',
            field=models.TextField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
