# Generated by Django 3.0.7 on 2020-06-25 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_classdata_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcontent',
            name='subject_name',
            field=models.TextField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
