# Generated by Django 3.0.7 on 2020-06-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_classcontent_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcontent',
            name='contributer_image',
            field=models.ImageField(upload_to='ContributerImage'),
        ),
        migrations.AlterField(
            model_name='classcontent',
            name='contributer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='classcontent',
            name='subject_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='classdata',
            name='class_id',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='leveldata',
            name='module_name',
            field=models.CharField(max_length=20),
        ),
    ]
