# Generated by Django 3.0.7 on 2020-06-30 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200628_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcontent',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
