# Generated by Django 3.0.7 on 2020-06-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0002_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BootcampData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bootcamp_name', models.CharField(max_length=30)),
                ('bootcamp_duration', models.CharField(max_length=30)),
                ('bootcamp_location', models.CharField(max_length=30)),
            ],
        ),
    ]
